# Classification model 1 (KNN)

In [ ]:
#KNN
#https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/
#numpy and pandas initialization
#https://towardsdatascience.com/building-a-k-nearest-neighbors-k-nn-model-with-scikit-learn-51209555453a
import numpy as np
import pandas as pd

#Loading the PlayTennis data
df = pd.read_csv("depression.csv")

df

physical condition mental condition marital status unemployment depression
0              normal           normal        married          yes         no
1              normal           normal        married           no         no
2             fatigue           normal        married          yes        yes
3       heart disease            guilt        married          yes        yes
4       heart disease          anxiety      unmarried          yes        yes
5       heart disease          anxiety      unmarried           no         no
6             fatigue          anxiety      unmarried           no        yes
7              normal            guilt        married          yes         no
8              normal          anxiety      unmarried          yes        yes
9       heart disease            guilt      unmarried          yes        yes
10             normal            guilt      unmarried           no        yes
11            fatigue            guilt        married           no        yes
12            fatigue           normal      unmarried          yes        yes
13      heart disease            guilt        married           no         no
14            fatigue            guilt      unmarried          yes        yes
15      heart disease            guilt      unmarried          yes         no
16             normal           normal        married           no         no
17             normal            guilt      unmarried           no         no

In [ ]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()

df['physical condition'] = Le.fit_transform(df['physical condition'])
df['mental condition'] = Le.fit_transform(df['mental condition'])
df['marital status'] = Le.fit_transform(df['marital status'])
df['unemployment'] = Le.fit_transform(df['unemployment'])
df['depression'] = Le.fit_transform(df['depression'])
#df['hallucinations'] = Le.fit_transform(df['hallucinations'])
#df['suicidal'] = Le.fit_transform(df['suicidal'])
df


physical condition  mental condition  marital status  unemployment  \
0                    2                 2               0             1   
1                    2                 2               0             0   
2                    0                 2               0             1   
3                    1                 1               0             1   
4                    1                 0               1             1   
5                    1                 0               1             0   
6                    0                 0               1             0   
7                    2                 1               0             1   
8                    2                 0               1             1   
9                    1                 1               1             1   
10                   2                 1               1             0   
11                   0                 1               0             0   
12                   0                 2               1             1   
13                   1                 1               0             0   
14                   0                 1               1             1   
15                   1                 1               1             1   
16                   2                 2               0             0   
17                   2                 1               1             0   

    depression  
0            0  
1            0  
2            1  
3            1  
4            1  
5            0  
6            1  
7            0  
8            1  
9            1  
10           1  
11           1  
12           1  
13           0  
14           1  
15           0  
16           0  
17           0

In [ ]:
y = df['depression']
X = df.drop(['depression'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import  confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[1 0]
 [1 2]]


In [ ]:
import sklearn.metrics as metrics

print('f1 score is ',metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred)))
print('precision score is ',metrics.precision_score(y_test, y_pred, labels=np.unique(y_pred)))
print('accuracy is ',metrics.accuracy_score(y_test, y_pred))
print('recall score is ',metrics.recall_score(y_test, y_pred))

f1 score is  0.8
precision score is  1.0
accuracy is  0.75
recall score is  0.6666666666666666


In [ ]:
#CROSS VALIDATION
from sklearn.model_selection import cross_val_score
import numpy as np
#create a new KNN model
knn_cv = KNeighborsClassifier(n_neighbors=3)
#train model with cv of 5 
cv_scores = cross_val_score(knn_cv, X, y, cv=5)
#print each cv score (accuracy) and average them
print(cv_scores)
print("cv_scores mean:{}".format(np.mean(cv_scores)))


[0.75       0.75       0.25       0.66666667 1.        ]
cv_scores mean:0.6833333333333333


# Decision Tree

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import  confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[0 2]
 [1 1]]


In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import  confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[0 2]
 [1 1]]


In [ ]:
import sklearn.metrics as metrics

print('f1 score is ',metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred)))
print('precision score is ',metrics.precision_score(y_test, y_pred, labels=np.unique(y_pred)))
print('accuracy is ',metrics.accuracy_score(y_test, y_pred))
print('recall score is ',metrics.recall_score(y_test, y_pred))

f1 score is  0.4
precision score is  0.3333333333333333
accuracy is  0.25
recall score is  0.5


In [ ]:
#CROSS VALIDATION
from sklearn.model_selection import cross_val_score
import numpy as np

cvx = DecisionTreeClassifier()
#train model with cv of 5 
cv_scores = cross_val_score(cvx, X, y, cv=5)
#print each cv score (accuracy) and average them
print(cv_scores)
print("cv_scores mean:{}".format(np.mean(cv_scores)))


[0.75       0.5        0.25       0.66666667 0.66666667]
cv_scores mean:0.5666666666666667


# Naive Bayes

In [ ]:
y = df['depression']
X = df.drop(['depression'],axis=1)



#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)

In [ ]:
from sklearn.metrics import  confusion_matrix
print(confusion_matrix(y_test, y_pred))

import sklearn.metrics as metrics

print('f1 score is ',metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred)))
print('precision score is ',metrics.precision_score(y_test, y_pred, labels=np.unique(y_pred)))
print('accuracy is ',metrics.accuracy_score(y_test, y_pred))
print('recall score is ',metrics.recall_score(y_test, y_pred))

#CROSS VALIDATION
from sklearn.model_selection import cross_val_score
import numpy as np

cvx = GaussianNB()
#train model with cv of 5 
cv_scores = cross_val_score(cvx, X, y, cv=5)
#print each cv score (accuracy) and average them
print(cv_scores)
print("cv_scores mean:{}".format(np.mean(cv_scores)))


[[0 2]
 [0 2]]
f1 score is  0.6666666666666666
precision score is  0.5
accuracy is  0.5
recall score is  1.0
[0.75       0.75       0.25       0.66666667 1.        ]
cv_scores mean:0.6833333333333333


# SVM

In [ ]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
from sklearn.metrics import  confusion_matrix
print(confusion_matrix(y_test, y_pred))


[[0 2]
 [1 1]]


In [ ]:
import sklearn.metrics as metrics

print('f1 score is ',metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred)))
print('precision score is ',metrics.precision_score(y_test, y_pred, labels=np.unique(y_pred)))
print('accuracy is ',metrics.accuracy_score(y_test, y_pred))
print('recall score is ',metrics.recall_score(y_test, y_pred))

f1 score is  0.4
precision score is  0.3333333333333333
accuracy is  0.25
recall score is  0.5


In [ ]:
from sklearn.model_selection import cross_val_score
import numpy as np

cvx =svm.SVC(kernel='linear')
#train model with cv of 5 
cv_scores = cross_val_score(cvx, X, y, cv=5)
#print each cv score (accuracy) and average them
print(cv_scores)
print("cv_scores mean:{}".format(np.mean(cv_scores)))

[0.75       0.75       0.5        0.66666667 1.        ]
cv_scores mean:0.7333333333333333


# Random Forest

In [ ]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [ ]:
import sklearn.metrics as metrics

print('accuracy is ',metrics.accuracy_score(y_test, y_pred))

accuracy is  0.5


In [ ]:
from sklearn.model_selection import cross_val_score
import numpy as np

cvx =RandomForestClassifier(n_estimators=100)
#train model with cv of 5 
cv_scores = cross_val_score(cvx, X, y, cv=5)
#print each cv score (accuracy) and average them
print(cv_scores)
print("cv_scores mean:{}".format(np.mean(cv_scores)))

[0.75       0.5        0.5        0.66666667 0.66666667]
cv_scores mean:0.6166666666666666
